title: CV | A jekyll template
description:  ESTA PLANTILLA ES PARA GONZALO BURGOS
url: https://ismaryro.github.io/jekyll-cv/
baseurl: 'jekyll-cv'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
